// carstvgrecomp - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/carstvgrecomp_config.h"
#include "generated/carstvgrecomp_init.h"

#include <rex/rex_app.h>

class CarstvgrecompApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<CarstvgrecompApp>(new CarstvgrecompApp(ctx, "carstvgrecomp",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }
};

REX_DEFINE_APP(carstvgrecomp, CarstvgrecompApp::Create)
